name       : fwupd-efi
version    : '1.4'
release    : 1
source     :
    - https://github.com/fwupd/fwupd-efi/releases/download/1.4/fwupd-efi-1.4.tar.xz : 27ddbc0a4e3209543eab49e69f1a014eb9ed95f93ff51f966f31082d3b7bffbc
license    : LGPL-2.1-or-later
component  : system.utils
summary    : EFI Application used by uefi-capsule plugin in fwupd
description: |
    EFI Application used by uefi-capsule plugin in fwupd
builddeps  :
    - gnu-efi-devel
    - python-pefile
    - sbsigntools
setup      : |
    %meson_configure \
        --libexecdir="lib64/fwupd" \
        -D efi_sbat_distro_id="com.solus-project" \
        -D efi_sbat_distro_summary="Solus Project" \
        -D efi_sbat_distro_pkgname="fwupd-efi" \
        -D efi_sbat_distro_version="%version%" \
        -D efi_sbat_distro_url="https://dev.getsol.us/source/fwupd-efi"
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Sign with our MOK if we have the secureboot-keys submodule checked out.
    if [[ -e $pkgfiles/secureboot-keys/MOK.key ]]; then
        sbsign --key $pkgfiles/secureboot-keys/MOK.key \
               --cert $pkgfiles/secureboot-keys/MOK.crt \
               --output $installdir/usr/lib64/fwupd/fwupd/efi/fwupdx64.efi.signed \
               $installdir/usr/lib64/fwupd/fwupd/efi/fwupdx64.efi
    fi

    # Ensure fwupd can find the shim
    ln -sf /usr/lib/shim/shimx64.efi $installdir/usr/lib64/fwupd/fwupd/efi/bootloaderx64.efi.signed
check      : |
    %ninja_check
